let currencyMaster = [
  {
    currencycode: "AED",
    currencyName: "Dirham",
    countryname: "United Arab Emirates",
    countrycode: "AE",
    rate: 0.04701139127095866,
    imageUrl: "https://flagcdn.com/h40/ae.png",
    currencySymbol: "د.إ",
  },
  {
    currencycode: "AFN",
    currencyName: "Afghani",
    countryname: "Afghanistan",
    countrycode: "AF",
    rate: 1.1455266862920772,
    imageUrl: "https://flagcdn.com/h40/af.png",
    currencySymbol: "؋",
  },
  {
    currencycode: "AMD",
    currencyName: "Dram",
    countryname: "Armenia",
    countrycode: "AM",
    rate: 6.1453858953027005,
    imageUrl: "https://flagcdn.com/h40/am.png",
  },
  {
    currencycode: "AUD",
    currencyName: "Dollar",
    countryname: "Australia",
    countrycode: "AU",
    rate: 0.018432100345577882,
    imageUrl: "https://flagcdn.com/h40/au.png",
    currencySymbol: "$",
  },
  {
    currencycode: "AZN",
    currencyName: "Manat",
    countryname: "Azerbaijan",
    countrycode: "AZ",
    rate: 0.021758607449123255,
    imageUrl: "https://flagcdn.com/h40/az.png",
    currencySymbol: "₼",
  },
  {
    currencycode: "BHD",
    currencyName: "Dinar",
    countryname: "Bahrain",
    countrycode: "BH",
    rate: 0.004825291181364393,
    imageUrl: "https://flagcdn.com/h40/bh.png",
  },
  {
    currencycode: "SGD",
    currencyName: "Dollar",
    countryname: "Brunei Darussalam",
    countrycode: "BN",
    rate: 0.01782669909125816,
    imageUrl: "https://flagcdn.com/h40/bn.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Andorra",
    countrycode: "AD",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/ad.png",
    currencySymbol: "€",
  },
  {
    currencycode: "BRL",
    currencyName: "Real",
    countryname: "Brazil",
    countrycode: "BR",
    rate: 0.0654870088314348,
    imageUrl: "https://flagcdn.com/h40/br.png",
    currencySymbol: "R$",
  },
  {
    currencycode: "BWP",
    currencyName: "Pula",
    countryname: "Botswana",
    countrycode: "BW",
    rate: 0.15701139127095867,
    imageUrl: "https://flagcdn.com/h40/bw.png",
    currencySymbol: "P",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Antigua and Barbuda",
    countrycode: "AG",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ag.png",
    currencySymbol: "$",
  },
  {
    currencycode: "XAF",
    currencyName: "Franc",
    countryname: "Central African Republic",
    countrycode: "CF",
    rate: 8.081004735696917,
    imageUrl: "https://flagcdn.com/h40/cf.png",
  },
  {
    currencycode: "CAD",
    currencyName: "Dollar",
    countryname: "Canada",
    countrycode: "CA",
    rate: 0.016597977729425315,
    imageUrl: "https://flagcdn.com/h40/ca.png",
    currencySymbol: "$",
  },
  {
    currencycode: "CHF",
    currencyName: "Franc",
    countryname: "Switzerland",
    countrycode: "CH",
    rate: 0.01282221937795981,
    imageUrl: "https://flagcdn.com/h40/ch.png",
    currencySymbol: "CHF",
  },
  {
    currencycode: "XOF",
    currencyName: "CFA Franc",
    countryname: "Cote d'Ivoire",
    countrycode: "CI",
    rate: 7.999488032765903,
    imageUrl: "https://flagcdn.com/h40/ci.png",
  },
  {
    currencycode: "NZD",
    currencyName: "Dollar",
    countryname: "Cook Islands",
    countrycode: "CK",
    rate: 0.020505567643670806,
    imageUrl: "https://flagcdn.com/h40/ck.png",
    currencySymbol: "$",
  },
  {
    currencycode: "CNY",
    currencyName: "Yuan",
    countryname: "China",
    countrycode: "CN",
    rate: 0.08593626007935493,
    imageUrl: "https://flagcdn.com/h40/cn.png",
    currencySymbol: "¥",
  },
  {
    currencycode: "COP",
    currencyName: "Peso",
    countryname: "Colombia",
    countrycode: "CO",
    rate: 50.17496352233457,
    imageUrl: "https://flagcdn.com/h40/co.png",
    currencySymbol: "$",
  },
  {
    currencycode: "CVE",
    currencyName: "Escudo",
    countryname: "Cape Verde",
    countrycode: "CV",
    rate: 1.3592730065275822,
    imageUrl: "https://flagcdn.com/h40/cv.png",
  },
  {
    currencycode: "DZD",
    currencyName: "Dinar",
    countryname: "Algeria",
    countrycode: "DZ",
    rate: 1.8777345449891207,
    imageUrl: "https://flagcdn.com/h40/dz.png",
  },
  {
    currencycode: "DKK",
    currencyName: "Krone",
    countryname: "Denmark",
    countrycode: "DK",
    rate: 0.09167413285549725,
    imageUrl: "https://flagcdn.com/h40/dk.png",
    currencySymbol: "kr",
  },
  {
    currencycode: "GBP",
    currencyName: "Pound",
    countryname: "Falkland Islands",
    countrycode: "FK",
    rate: 0.010614360680916422,
    imageUrl: "https://flagcdn.com/h40/fk.png",
    currencySymbol: "£",
  },
  {
    currencycode: "FJD",
    currencyName: "Dollar",
    countryname: "Fiji",
    countrycode: "FJ",
    rate: 0.028080122872136185,
    imageUrl: "https://flagcdn.com/h40/fj.png",
    currencySymbol: "$",
  },
  {
    currencycode: "GEL",
    currencyName: "Lari",
    countryname: "Georgia",
    countrycode: "GE",
    rate: 0.037629591706130804,
    imageUrl: "https://flagcdn.com/h40/ge.png",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Anguilla",
    countrycode: "AI",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ai.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Albania",
    countrycode: "AL",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/al.png",
    currencySymbol: "€",
  },
  {
    currencycode: "GTQ",
    currencyName: "Quetzal",
    countryname: "Guatemala",
    countrycode: "GT",
    rate: 0.09889543069243568,
    imageUrl: "https://flagcdn.com/h40/gt.png",
    currencySymbol: "Q",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Argentina",
    countrycode: "AR",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ar.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Angola",
    countrycode: "AO",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ao.png",
    currencySymbol: "$",
  },
  {
    currencycode: "IDR",
    currencyName: "Rupah",
    countryname: "Indonesia",
    countrycode: "ID",
    rate: 188.22325355177267,
    imageUrl: "https://flagcdn.com/h40/id.png",
    currencySymbol: "Rp",
  },
  {
    currencycode: "HKD",
    currencyName: "Dollar",
    countryname: "Hong Kong",
    countrycode: "HK",
    rate: 0.1004722897734545,
    imageUrl: "https://flagcdn.com/h40/hk.png",
    currencySymbol: "$",
  },
  {
    currencycode: "ILS",
    currencyName: "Shekel",
    countryname: "Israel",
    countrycode: "IL",
    rate: 0.044135415333418665,
    imageUrl: "https://flagcdn.com/h40/il.png",
    currencySymbol: "₪",
  },
  {
    currencycode: "INR",
    currencyName: "Rupee",
    countryname: "India",
    countrycode: "IN",
    rate: 1.0000575963138358,
    imageUrl: "https://flagcdn.com/h40/in.png",
    currencySymbol: "₹",
  },
  {
    currencycode: "IRR",
    currencyName: "Rial",
    countryname: "Iran",
    countrycode: "IR",
    rate: 537.8855753231793,
    imageUrl: "https://flagcdn.com/h40/ir.png",
    currencySymbol: "﷼",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Aruba",
    countrycode: "AW",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/aw.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Austria",
    countrycode: "AT",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/at.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "American Samoa",
    countrycode: "AS",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/as.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Bosnia and Herzegovina",
    countrycode: "BA",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/ba.png",
    currencySymbol: "€",
  },
  {
    currencycode: "KRW",
    currencyName: "Won",
    countryname: "Korea, South",
    countrycode: "KR",
    rate: 16.52911813643927,
    imageUrl: "https://flagcdn.com/h40/kr.png",
    currencySymbol: "₩",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Barbados",
    countrycode: "BB",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/bb.png",
    currencySymbol: "$",
  },
  {
    currencycode: "JPY",
    currencyName: "Yen",
    countryname: "Japan",
    countrycode: "JP",
    rate: 1.7216178164597464,
    imageUrl: "https://flagcdn.com/h40/jp.png",
    currencySymbol: "¥",
  },
  {
    currencycode: "JOD",
    currencyName: "Dinar",
    countryname: "Jordan",
    countrycode: "JO",
    rate: 0.00907461922436964,
    imageUrl: "https://flagcdn.com/h40/jo.png",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Burkina Faso",
    countrycode: "BF",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/bf.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Belgium",
    countrycode: "BE",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/be.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Bulgaria",
    countrycode: "BG",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/bg.png",
    currencySymbol: "€",
  },
  {
    currencycode: "KZT",
    currencyName: "Tenge",
    countryname: "Kazakhstan",
    countrycode: "KZ",
    rate: 5.624693459618584,
    imageUrl: "https://flagcdn.com/h40/kz.png",
    currencySymbol: "лв",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Bangladesh",
    countrycode: "BD",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/bd.png",
    currencySymbol: "$",
  },
  {
    currencycode: "KWD",
    currencyName: "Dinar",
    countryname: "Kuwait",
    countrycode: "KW",
    rate: 0.00393318827595034,
    imageUrl: "https://flagcdn.com/h40/kw.png",
  },
  {
    currencycode: "LSL",
    currencyName: "Loti",
    countryname: "Lesotho",
    countrycode: "LS",
    rate: 0.2059388199155254,
    imageUrl: "https://flagcdn.com/h40/ls.png",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Benin",
    countrycode: "BJ",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/bj.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Bermuda",
    countrycode: "BM",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/bm.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Burundi",
    countrycode: "BI",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/bi.png",
    currencySymbol: "$",
  },
  {
    currencycode: "MDL",
    currencyName: "Leu",
    countryname: "Moldova",
    countrycode: "MD",
    rate: 0.24486624856009215,
    imageUrl: "https://flagcdn.com/h40/md.png",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Saint Barthelemy",
    countrycode: "BL",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/bl.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Bonaire, Saint Eustatius and Saba",
    countrycode: "BQ",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/bq.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Bolivia",
    countrycode: "BO",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/bo.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Bahamas",
    countrycode: "BS",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/bs.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Bhutan",
    countrycode: "BT",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/bt.png",
    currencySymbol: "$",
  },
  {
    currencycode: "AUD",
    currencyName: "Dollar",
    countryname: "Cocos (Keeling) Islands",
    countrycode: "CC",
    rate: 0.018432100345577882,
    imageUrl: "https://flagcdn.com/h40/cc.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Belarus",
    countrycode: "BY",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/by.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Congo (Kinshasa)",
    countrycode: "CD",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/cd.png",
    currencySymbol: "$",
  },
  {
    currencycode: "XAF",
    currencyName: "Franc",
    countryname: "Cameroon",
    countrycode: "CM",
    rate: 8.081004735696917,
    imageUrl: "https://flagcdn.com/h40/cm.png",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Belize",
    countrycode: "BZ",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/bz.png",
    currencySymbol: "$",
  },
  {
    currencycode: "XPF",
    currencyName: "CFP Franc",
    countryname: "New Caledonia",
    countrycode: "NC",
    rate: 1.466786125687956,
    imageUrl: "https://flagcdn.com/h40/nc.png",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Cuba",
    countrycode: "CU",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/cu.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Cyprus",
    countrycode: "CY",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/cy.png",
    currencySymbol: "€",
  },
  {
    currencycode: "XAF",
    currencyName: "Franc",
    countryname: "Congo (Brazzaville)",
    countrycode: "CG",
    rate: 8.081004735696917,
    imageUrl: "https://flagcdn.com/h40/cg.png",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Dominica",
    countrycode: "DM",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/dm.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Curaçao",
    countrycode: "CW",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/cw.png",
    currencySymbol: "$",
  },
  {
    currencycode: "QAR",
    currencyName: "Riyal",
    countryname: "Qatar",
    countrycode: "QA",
    rate: 0.04666837322411366,
    imageUrl: "https://flagcdn.com/h40/qa.png",
    currencySymbol: "﷼",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Haiti",
    countrycode: "HT",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ht.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Chile",
    countrycode: "CL",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/cl.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Ireland",
    countrycode: "IE",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/ie.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Costa Rica",
    countrycode: "CR",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/cr.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Guinea",
    countrycode: "GN",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/gn.png",
    currencySymbol: "€",
  },
  {
    currencycode: "MYR",
    currencyName: "Ringgit",
    countryname: "Malaysia",
    countrycode: "MY",
    rate: 0.0564891846921797,
    imageUrl: "https://flagcdn.com/h40/my.png",
    currencySymbol: "RM",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Jamaica",
    countrycode: "JM",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/jm.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Cayman Islands",
    countrycode: "KY",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ky.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Cambodia",
    countrycode: "KH",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/kh.png",
    currencySymbol: "$",
  },
  {
    currencycode: "AUD",
    currencyName: "Dollar",
    countryname: "Kiribati",
    countrycode: "KI",
    rate: 0.018432100345577882,
    imageUrl: "https://flagcdn.com/h40/ki.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Ecuador",
    countrycode: "EC",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ec.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Czech Republic",
    countrycode: "CZ",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/cz.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Spain",
    countrycode: "ES",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/es.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Egypt",
    countrycode: "EG",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/eg.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Ethiopia",
    countrycode: "ET",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/et.png",
    currencySymbol: "$",
  },
  {
    currencycode: "NOK",
    currencyName: "Kroner",
    countryname: "Norway",
    countrycode: "NO",
    rate: 0.12834762575195185,
    imageUrl: "https://flagcdn.com/h40/no.png",
    currencySymbol: "kr",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Eritrea",
    countrycode: "ER",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/er.png",
    currencySymbol: "$",
  },
  {
    currencycode: "MZN",
    currencyName: "Metical",
    countryname: "Mozambique",
    countrycode: "MZ",
    rate: 0.8169717138103161,
    imageUrl: "https://flagcdn.com/h40/mz.png",
    currencySymbol: "MT",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Micronesia",
    countrycode: "FM",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/fm.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Dominican Republic",
    countrycode: "DO",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/do.png",
    currencySymbol: "$",
  },
  {
    currencycode: "DKK",
    currencyName: "Krone",
    countryname: "Faroe Islands",
    countrycode: "FO",
    rate: 0.09167413285549725,
    imageUrl: "https://flagcdn.com/h40/fo.png",
    currencySymbol: "kr",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Gabon",
    countrycode: "GA",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/ga.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "France",
    countrycode: "FR",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/fr.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Estonia",
    countrycode: "EE",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/ee.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Germany",
    countrycode: "DE",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/de.png",
    currencySymbol: "€",
  },
  {
    currencycode: "OMR",
    currencyName: "Riyal",
    countryname: "Oman",
    countrycode: "OM",
    rate: 0.004926404710098554,
    imageUrl: "https://flagcdn.com/h40/om.png",
    currencySymbol: "﷼",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Grenada",
    countrycode: "GD",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/gd.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Djibouti",
    countrycode: "DJ",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/dj.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Ghana",
    countrycode: "GH",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/gh.png",
    currencySymbol: "$",
  },
  {
    currencycode: "GBP",
    currencyName: "Pound",
    countryname: "United Kingdom",
    countrycode: "GB",
    rate: 0.010614360680916422,
    imageUrl: "https://flagcdn.com/h40/gb.png",
    currencySymbol: "£",
  },
  {
    currencycode: "PHP",
    currencyName: "Piso",
    countryname: "Philippines",
    countrycode: "PH",
    rate: 0.6823985664917446,
    imageUrl: "https://flagcdn.com/h40/ph.png",
    currencySymbol: "₱",
  },
  {
    currencycode: "PGK",
    currencyName: "Kina",
    countryname: "Papua New Guinea",
    countrycode: "PG",
    rate: 0.04566875719953923,
    imageUrl: "https://flagcdn.com/h40/pg.png",
  },
  {
    currencycode: "PKR",
    currencyName: "Rupee",
    countryname: "Pakistan",
    countrycode: "PK",
    rate: 2.6501292717266094,
    imageUrl: "https://flagcdn.com/h40/pk.png",
    currencySymbol: "₨",
  },
  {
    currencycode: "GBP",
    currencyName: "Pound",
    countryname: "Gibraltar",
    countrycode: "GI",
    rate: 0.010614360680916422,
    imageUrl: "https://flagcdn.com/h40/gi.png",
    currencySymbol: "£",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Gambia",
    countrycode: "GM",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/gm.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Guadeloupe",
    countrycode: "GP",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/gp.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Guinea-Bissau",
    countrycode: "GW",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/gw.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Equatorial Guinea",
    countrycode: "GQ",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/gq.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "French Guiana",
    countrycode: "GF",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/gf.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Guam",
    countrycode: "GU",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/gu.png",
    currencySymbol: "$",
  },
  {
    currencycode: "PLN",
    currencyName: "Zloty",
    countryname: "Poland",
    countrycode: "PL",
    rate: 0.05761039293485217,
    imageUrl: "https://flagcdn.com/h40/pl.png",
    currencySymbol: "zł",
  },
  {
    currencycode: "RUB",
    currencyName: "Ruble",
    countryname: "Russian Federation",
    countrycode: "RU",
    rate: 0.735952899014463,
    imageUrl: "https://flagcdn.com/h40/ru.png",
    currencySymbol: "₽",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Guyana",
    countrycode: "GY",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/gy.png",
    currencySymbol: "$",
  },
  {
    currencycode: "DKK",
    currencyName: "Krone",
    countryname: "Greenland",
    countrycode: "GL",
    rate: 0.09167413285549725,
    imageUrl: "https://flagcdn.com/h40/gl.png",
    currencySymbol: "kr",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Mauritius",
    countrycode: "MU",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/mu.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Macedonia",
    countrycode: "MK",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/mk.png",
    currencySymbol: "€",
  },
  {
    currencycode: "NAD",
    currencyName: "Dollar",
    countryname: "Namibia",
    countrycode: "NA",
    rate: 0.20577499040061437,
    imageUrl: "https://flagcdn.com/h40/na.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Saint Pierre and Miquelon",
    countrycode: "PM",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/pm.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Puerto Rico",
    countrycode: "PR",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/pr.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Northern Mariana Islands",
    countrycode: "MP",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/mp.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Honduras",
    countrycode: "HN",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/hn.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Serbia",
    countrycode: "RS",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/rs.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Madagascar",
    countrycode: "MG",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/mg.png",
    currencySymbol: "€",
  },
  {
    currencycode: "GBP",
    currencyName: "Pound",
    countryname: "Isle of Man",
    countrycode: "IM",
    rate: 0.010614360680916422,
    imageUrl: "https://flagcdn.com/h40/im.png",
    currencySymbol: "£",
  },
  {
    currencycode: "SAR",
    currencyName: "Riyal",
    countryname: "Saudi Arabia",
    countrycode: "SA",
    rate: 0.048019966722129784,
    imageUrl: "https://flagcdn.com/h40/sa.png",
    currencySymbol: "﷼",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Mauritania",
    countrycode: "MR",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/mr.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Romania",
    countrycode: "RO",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/ro.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Reunion",
    countrycode: "RE",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/re.png",
    currencySymbol: "€",
  },
  {
    currencycode: "SEK",
    currencyName: "Krona",
    countryname: "Sweden",
    countrycode: "SE",
    rate: 0.13122616152566235,
    imageUrl: "https://flagcdn.com/h40/se.png",
    currencySymbol: "kr",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Rwanda",
    countrycode: "RW",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/rw.png",
    currencySymbol: "$",
  },
  {
    currencycode: "AUD",
    currencyName: "Dollar",
    countryname: "Solomon Islands",
    countrycode: "SB",
    rate: 0.018432100345577882,
    imageUrl: "https://flagcdn.com/h40/sb.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Seychelles",
    countrycode: "SC",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/sc.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Italy",
    countrycode: "IT",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/it.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Iceland",
    countrycode: "IS",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/is.png",
    currencySymbol: "€",
  },
  {
    currencycode: "THB",
    currencyName: "Baht",
    countryname: "Thailand",
    countrycode: "TH",
    rate: 0.4475745552284654,
    imageUrl: "https://flagcdn.com/h40/th.png",
    currencySymbol: "฿",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Greece",
    countrycode: "GR",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/gr.png",
    currencySymbol: "€",
  },
  {
    currencycode: "GBP",
    currencyName: "Pound",
    countryname: "Saint Helena",
    countrycode: "SH",
    rate: 0.010614360680916422,
    imageUrl: "https://flagcdn.com/h40/sh.png",
    currencySymbol: "£",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Saint Kitts and Nevis",
    countrycode: "KN",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/kn.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Liberia",
    countrycode: "LR",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/lr.png",
    currencySymbol: "$",
  },
  {
    currencycode: "TWD",
    currencyName: "Dollar",
    countryname: "Taiwan",
    countrycode: "TW",
    rate: 0.38052604633303466,
    imageUrl: "https://flagcdn.com/h40/tw.png",
    currencySymbol: "NT$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Kenya",
    countrycode: "KE",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ke.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Slovenia",
    countrycode: "SI",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/si.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Finland",
    countrycode: "FI",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/fi.png",
    currencySymbol: "€",
  },
  {
    currencycode: "CHF",
    currencyName: "Franc",
    countryname: "Liechtenstein",
    countrycode: "LI",
    rate: 0.01282221937795981,
    imageUrl: "https://flagcdn.com/h40/li.png",
    currencySymbol: "CHF",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Comoros",
    countrycode: "KM",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/km.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Saint Lucia",
    countrycode: "LC",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/lc.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Croatia",
    countrycode: "HR",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/hr.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Latvia",
    countrycode: "LV",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/lv.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Morocco",
    countrycode: "MA",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/ma.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Libya",
    countrycode: "LY",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/ly.png",
    currencySymbol: "€",
  },
  {
    currencycode: "ZAR",
    currencyName: "Rand",
    countryname: "South Africa",
    countrycode: "ZA",
    rate: 0.205108153078203,
    imageUrl: "https://flagcdn.com/h40/za.png",
    currencySymbol: "R",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Luxembourg",
    countrycode: "LU",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/lu.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Lithuania",
    countrycode: "LT",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/lt.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Montenegro",
    countrycode: "ME",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/me.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Saint Martin",
    countrycode: "MF",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/mf.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Myanmar",
    countrycode: "MM",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/mm.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Monaco",
    countrycode: "MC",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/mc.png",
    currencySymbol: "€",
  },
  {
    currencycode: "XOF",
    currencyName: "CFA Franc",
    countryname: "Mali",
    countrycode: "ML",
    rate: 7.999488032765903,
    imageUrl: "https://flagcdn.com/h40/ml.png",
  },
  {
    currencycode: "HKD",
    currencyName: "Dollar",
    countryname: "Macau",
    countrycode: "MO",
    rate: 0.1004722897734545,
    imageUrl: "https://flagcdn.com/h40/mo.png",
    currencySymbol: "$",
  },
  {
    currencycode: "VUV",
    currencyName: "Vatu",
    countryname: "Vanuatu",
    countrycode: "VU",
    rate: 1.4947369768334826,
    imageUrl: "https://flagcdn.com/h40/vu.png",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Martinique",
    countrycode: "MQ",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/mq.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Laos",
    countrycode: "LA",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/la.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Mongolia",
    countrycode: "MN",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/mn.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "San Marino",
    countrycode: "SM",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/sm.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Samoa",
    countrycode: "WS",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ws.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Sierra Leone",
    countrycode: "SL",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/sl.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Malta",
    countrycode: "MT",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/mt.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Malawi",
    countrycode: "MW",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/mw.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Netherlands",
    countrycode: "NL",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/nl.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Mexico",
    countrycode: "MX",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/mx.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Nigeria",
    countrycode: "NG",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ng.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Maldives",
    countrycode: "MV",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/mv.png",
    currencySymbol: "$",
  },
  {
    currencycode: "AUD",
    currencyName: "Dollar",
    countryname: "Nauru",
    countrycode: "NR",
    rate: 0.018432100345577882,
    imageUrl: "https://flagcdn.com/h40/nr.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Niger",
    countrycode: "NE",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/ne.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Panama",
    countrycode: "PA",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/pa.png",
    currencySymbol: "$",
  },
  {
    currencycode: "NZD",
    currencyName: "Dollar",
    countryname: "New Zealand",
    countrycode: "NZ",
    rate: 0.020505567643670806,
    imageUrl: "https://flagcdn.com/h40/nz.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Nicaragua",
    countrycode: "NI",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ni.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Lebanon",
    countrycode: "LB",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/lb.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Peru",
    countrycode: "PE",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/pe.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Nepal",
    countrycode: "NP",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/np.png",
    currencySymbol: "$",
  },
  {
    currencycode: "NZD",
    currencyName: "Dollar",
    countryname: "Niue",
    countrycode: "NU",
    rate: 0.020505567643670806,
    imageUrl: "https://flagcdn.com/h40/nu.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Hungary",
    countrycode: "HU",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/hu.png",
    currencySymbol: "€",
  },
  {
    currencycode: "AUD",
    currencyName: "Dollar",
    countryname: "Norfolk Island",
    countrycode: "NF",
    rate: 0.018432100345577882,
    imageUrl: "https://flagcdn.com/h40/nf.png",
    currencySymbol: "$",
  },
  {
    currencycode: "UAH",
    currencyName: "Hryvnia",
    countryname: "Ukraine",
    countrycode: "UA",
    rate: 0.38166261359273007,
    imageUrl: "https://flagcdn.com/h40/ua.png",
    currencySymbol: "₴",
  },
  {
    currencycode: "SZL",
    currencyName: "Lilangeni",
    countryname: "Swaziland",
    countrycode: "SZ",
    rate: 0.20520286701651091,
    imageUrl: "https://flagcdn.com/h40/sz.png",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Palestine",
    countrycode: "PS",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ps.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Kyrgyzstan",
    countrycode: "KG",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/kg.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Iraq",
    countrycode: "IQ",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/iq.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Portugal",
    countrycode: "PT",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/pt.png",
    currencySymbol: "€",
  },
  {
    currencycode: "XPF",
    currencyName: "CFP Franc",
    countryname: "French Polynesia",
    countrycode: "PF",
    rate: 1.466786125687956,
    imageUrl: "https://flagcdn.com/h40/pf.png",
  },
  {
    currencycode: "SGD",
    currencyName: "Dollar",
    countryname: "Singapore",
    countrycode: "SG",
    rate: 0.01782669909125816,
    imageUrl: "https://flagcdn.com/h40/sg.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Palau",
    countrycode: "PW",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/pw.png",
    currencySymbol: "$",
  },
  {
    currencycode: "XOF",
    currencyName: "CFA Franc",
    countryname: "Senegal",
    countrycode: "SN",
    rate: 7.999488032765903,
    imageUrl: "https://flagcdn.com/h40/sn.png",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Sri Lanka",
    countrycode: "LK",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/lk.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Marshall Islands",
    countrycode: "MH",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/mh.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Somalia",
    countrycode: "SO",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/so.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Suriname",
    countrycode: "SR",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/sr.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Sao Tome and Principe",
    countrycode: "ST",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/st.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Tonga",
    countrycode: "TO",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/to.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Syrian Arab Republic",
    countrycode: "SY",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/sy.png",
    currencySymbol: "$",
  },
  {
    currencycode: "XAF",
    currencyName: "Franc",
    countryname: "Chad",
    countrycode: "TD",
    rate: 8.081004735696917,
    imageUrl: "https://flagcdn.com/h40/td.png",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Sint Maarten",
    countrycode: "SX",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/sx.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Tanzania",
    countrycode: "TZ",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/tz.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Tajikistan",
    countrycode: "TJ",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/tj.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "South Sudan",
    countrycode: "SS",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ss.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Trinidad and Tobago",
    countrycode: "TT",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/tt.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Tunisia",
    countrycode: "TN",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/tn.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Venezuela",
    countrycode: "VE",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ve.png",
    currencySymbol: "$",
  },
  {
    currencycode: "XPF",
    currencyName: "CFP Franc",
    countryname: "Wallis and Futuna Islands",
    countrycode: "WF",
    rate: 1.466786125687956,
    imageUrl: "https://flagcdn.com/h40/wf.png",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Togo",
    countrycode: "TG",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/tg.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "United States of America",
    countrycode: "US",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/us.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Virgin Islands, U.S.",
    countrycode: "VI",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/vi.png",
    currencySymbol: "$",
  },
  {
    currencycode: "RUB",
    currencyName: "Ruble",
    countryname: "Abkhazia",
    countrycode: "XA",
    rate: 0.735952899014463,
    imageUrl: "https://flagcdn.com/h40/xa.png",
    currencySymbol: "₽",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "East Timor",
    countrycode: "TL",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/tl.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Saint Vincent and the Grenadines",
    countrycode: "VC",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/vc.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Turks and Caicos Islands",
    countrycode: "TC",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/tc.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Turkey",
    countrycode: "TR",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/tr.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Uruguay",
    countrycode: "UY",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/uy.png",
    currencySymbol: "$",
  },
  {
    currencycode: "AUD",
    currencyName: "Dollar",
    countryname: "Tuvalu",
    countrycode: "TV",
    rate: 0.018432100345577882,
    imageUrl: "https://flagcdn.com/h40/tv.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Uganda",
    countrycode: "UG",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ug.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Kosovo",
    countrycode: "XK",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/xk.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Mayotte",
    countrycode: "YT",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/yt.png",
    currencySymbol: "€",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Northern Cyprus",
    countrycode: "XY",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/xy.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Yemen",
    countrycode: "YE",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ye.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Vietnam",
    countrycode: "VN",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/vn.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Zimbabwe",
    countrycode: "ZW",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/zw.png",
    currencySymbol: "$",
  },
  {
    currencycode: "RUB",
    currencyName: "Ruble",
    countryname: "Crimea",
    countrycode: "XC",
    rate: 0.735952899014463,
    imageUrl: "https://flagcdn.com/h40/xc.png",
    currencySymbol: "₽",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Montserrat",
    countrycode: "MS",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/ms.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Zambia",
    countrycode: "ZM",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/zm.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Paraguay",
    countrycode: "PY",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/py.png",
    currencySymbol: "$",
  },
  {
    currencycode: "EUR",
    currencyName: "Euro",
    countryname: "Slovakia",
    countrycode: "SK",
    rate: 0.012323051324715218,
    imageUrl: "https://flagcdn.com/h40/sk.png",
    currencySymbol: "€",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Virgin Islands, British",
    countrycode: "VG",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/vg.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Uzbekistan",
    countrycode: "UZ",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/uz.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "El Salvador",
    countrycode: "SV",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/sv.png",
    currencySymbol: "$",
  },
  {
    currencycode: "USD",
    currencyName: "Dollar",
    countryname: "Turkmenistan",
    countrycode: "TM",
    rate: 0.012799180852425445,
    imageUrl: "https://flagcdn.com/h40/tm.png",
    currencySymbol: "$",
  },
];

// let container= document.getElementById("shipToNavOptionMain");
function appendShipTo(singleData, container) {
  let box = document.createElement("div");
  let image = document.createElement("img");
  image.src = singleData.imageUrl;
  let countrySpan = document.createElement("span");
  countrySpan.innerText = singleData.countryname;
  box.append(image, countrySpan);
  box.addEventListener("click", function () {
    shiptoLocalData.countryFlag = singleData.imageUrl;
    shiptoLocalData.countryname = singleData.countryname;

    localStorage.setItem("shiptoLocalData", JSON.stringify(shiptoLocalData));
    window.location.reload();
  });
  container.append(box);
}

function applyShipFrom(singleData) {
  let box = document.createElement("div");
  let image = document.createElement("img");
  image.src = singleData.imageUrl;
  let countrySpan = document.createElement("span");
  countrySpan.innerText = singleData.countryname;
  box.append(image, countrySpan);
  box.addEventListener("click", function () {
    // filter option here
    document.getElementById("shipFromFilterOptionSpan").innerText =
      singleData.countryname;
  });

  let abcs = document.getElementById("shipFromDromDown");
  if (abcs) {
    abcs.append(box);
  }
}

let UniqueCurrency = {};

function dataConnect(master) {
  let container = document.getElementById("shipToDropDown");
  master.forEach(function (data) {
    applyShipFrom(data);
    appendShipTo(data, container);

    // currency data passed from here
    // currency data passed from here
    if (data.currencySymbol != undefined) {
      UniqueCurrency[data.currencycode] = [
        data.currencySymbol,
        data.rate.toFixed(3),
      ];
    }
  });
}
dataConnect(currencyMaster);

let shiptoLocalData = JSON.parse(localStorage.getItem("shiptoLocalData")) || {
  countryFlag: "https://flagcdn.com/h40/in.png",
  countryname: "India",
};

let currencyLocalData = JSON.parse(
  localStorage.getItem("currencyLocalData")
) || {
  currencycode: "INR",
  currencySymbol: "₹",
  rate: "1",
};

let arrM = [];
for (let k in UniqueCurrency) {
  let obj = {};
  obj[k] = UniqueCurrency[k];
  arrM.push(obj);
}
// console.log(Object.keys(arrM[0])[0])
let leftCurrContainer = document.getElementById("currencyNavleftIn");
let rightCurrContainer = document.getElementById("currencyNavRightIn");

function dataInsertCurrency(arr, start, end, container) {
  for (start; start < end; start++) {
    appendCurrency(arr[start], container);
  }
}
dataInsertCurrency(arrM, 0, 20, leftCurrContainer);
dataInsertCurrency(arrM, 21, 41, rightCurrContainer);

function appendCurrency(singleData, container) {
  let box = document.createElement("div");
  let symbolInNav = document.createElement("span");
  symbolInNav.innerText = singleData[Object.keys(singleData)[0]][0];
  let codeSpan = document.createElement("span");
  codeSpan.innerText = Object.keys(singleData)[0];
  box.append(symbolInNav, codeSpan);
  box.addEventListener("click", function () {
    currencyLocalData.currencycode = Object.keys(singleData)[0];
    currencyLocalData.currencySymbol =
      singleData[Object.keys(singleData)[0]][0];
    currencyLocalData.rate = singleData[Object.keys(singleData)[0]][1];
    console.log(currencyLocalData);
    localStorage.setItem(
      "currencyLocalData",
      JSON.stringify(currencyLocalData)
    );
    // master data update function
    // new rate and currency symbol
    updateAllLocalDataCurrency(
      singleData[Object.keys(singleData)[0]][1],
      singleData[Object.keys(singleData)[0]][0]
    );
    // master data update function
    window.location.reload();
  });
  container.append(box);
}

// update main dataBase in local =>masterDataBase
// update main dataBase in local =>masterDataBase
// let masterData = JSON.parse(localStorage.getItem("masterProduct")) || [];

// update main dataBase in local =>masterDataBase
function updateAllLocalDataCurrency(newRate, symbolGet) {
  // update the currency
  //   addDataTolocatStoreMaster();

  masterDataAllProduct.forEach(function (elem) {
    elem.offerPrice = (elem.offerPrice * newRate).toFixed(2);
    elem.actualPrice = (elem.actualPrice * newRate).toFixed(2);
    elem.currencySign = symbolGet;
  });
  localStorage.setItem(
    "masterAllLocalData",
    JSON.stringify(masterDataAllProduct)
  );
}

// currency code on nav update==========================================outside on nav
let currencycodeOnNav = document.getElementById("shipToNavCurrency");
currencycodeOnNav.innerText = currencyLocalData.currencycode;

// flag pic on nav update==================================================ouside on nav
let flagonnavdisplay = document.getElementById("shipToNavImg");
flagonnavdisplay.src = shiptoLocalData.countryFlag;
flagonnavdisplay.alt = shiptoLocalData.countryname;

// inside drop update==============================================================
// flag update in nav drp down update
let currencycodeOnNavIn = document.getElementById("shipTOCountry");
currencycodeOnNavIn.innerText = shiptoLocalData.countryname;

// flag pic in nav drop down update
let flagonnavdisplayIn = document.getElementById("countryShipTo");
flagonnavdisplayIn.src = shiptoLocalData.countryFlag;

// currency inside nav dropdown
let currencyNavInSymbol = document.getElementById("currencyNavInSymbolSpan");
currencyNavInSymbol.innerText = currencyLocalData.currencySymbol;

let currencycodeNavInCode = document.getElementById("currencyNavInCodeSpan");
currencycodeNavInCode.innerText = currencyLocalData.currencycode;
// UniqueCurrency
